### ISSUE TITLE
Add support for proxy

### ISSUE THREAD

**Issue by pranitbauva1997** [amitu/realm-starter#2]
I access outside network using the institute proxy for which I have set system-wide proxy in `/etc/environment` and again set at user-level in file `.bashrc` but it seems that Nix is unable to pick these up when running the pip command which involves fetching dependencies from outside network.

As a temporary workaround, I have added the following lines after [this line in `shell.nix`](https://github.com/amitu/realm-starter/blob/1e1d7dbf43a97dabc4714e39061201d810e354e8/shell.nix#L84) :

```
      export http_proxy=http://172.16.2.30:8080/
      export HTTP_PROXY=http://172.16.2.30:8080/
      export https_proxy=http://172.16.2.30:8080/
      export HTTPS_PROXY=http://172.16.2.30:8080/
```

which just works since I would have to create a separate branch to create a different development environment which led to think that there must be a better way to handle this?

**Comment by amitu** [comment]
We can put this conditionally in auto.sh, say you create a file .proxy.txt in root folder, and if it is found, "source" that file.

**Comment by pranitbauva1997** [comment]
@amitu This solution works. Thanks
